---
title: "Proyecto 1 - Minería de datos"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(dplyr)


data_matrimonios_2021 <- read_sav("matrimonios_2021.sav")
#View(data_matrimonios_2021)

data_matrimonios_2020 <- read_sav("matrimonios_2020.sav")
#View(data_matrimonios_2020)

data_matrimonios_2019 <- read_sav("matrimonios_2019.sav")
#View(data_matrimonios_2019)

data_matrimonios_2018 <- read_sav("matrimonios_2018.sav")
#View(data_matrimonios_2018)

data_matrimonios_2017 <- read_sav("matrimonios_2017.sav")
#View(data_matrimonios_2017)

data_matrimonios_2016 <- read_sav("matrimonios_2016.sav")
#View(data_matrimonios_2016)

data_matrimonios_2015 <- read_sav("matrimonios_2015.sav")
#View(data_matrimonios_2015)

data_matrimonios_2014 <- read_sav("matrimonios_2014.sav")
#View(data_matrimonios_2014)

data_matrimonios_2013 <- read_sav("matrimonios_2013.sav")
#View(data_matrimonios_2013)

data_matrimonios_2012 <- read_sav("matrimonios_2012.sav")
#View(data_matrimonios_2012)

data_matrimonios_2011 <- read_sav("matrimonios_2011.sav")
#View(data_matrimonios_2011)

data_matrimonios_2010 <- read_sav("matrimonios_2010.sav")
#View(data_matrimonios_2010)
```


```{r}
categorias <- c("01", "03", "11", "12", "13", "14", "21", "22", "23", "24", "25", "26", "31", "32", "33", "34", "35", "41", "42", "43", "44", "51", "52", "54", "61", "62", "71", "72", "73", "74", "75", "81", "82", "83", "91", "92", "93", "94", "95", "96")

data_matrimonios_2010$Ocuhom <- case_when(
  substr(data_matrimonios_2010$Ocuhom, 1, 2) %in% categorias ~ substr(data_matrimonios_2010$Ocuhom, 1, 2),
  substr(data_matrimonios_2010$Ocuhom, 1, 2) == "53" ~ "51",
  substr(data_matrimonios_2010$Ocuhom, 1, 2) == "97" ~ "NEOG",
  substr(data_matrimonios_2010$Ocuhom, 1, 2) == "99" ~ "IGNORADO",
  TRUE ~ data_matrimonios_2010$Ocuhom)
```

```{r}
unique(data_matrimonios_2010$Ocuhom)
```


```{r}
categorias <- c("01", "03", "11", "12", "13", "14", "21", "22", "23", "24", "25", "26", "31", "32", "33", "34", "35", "41", "42", "43", "44", "51", "52", "54", "61", "62", "71", "72", "73", "74", "75", "81", "82", "83", "91", "92", "93", "94", "95", "96")

data_matrimonios_2010$Ocumuj <- case_when(
  substr(data_matrimonios_2010$Ocumuj, 1, 2) %in% categorias ~ substr(data_matrimonios_2010$Ocumuj, 1, 2),
  substr(data_matrimonios_2010$Ocumuj, 1, 2) == "53" ~ "51",
  substr(data_matrimonios_2010$Ocumuj, 1, 2) == "97" ~ "NEOG",
  substr(data_matrimonios_2010$Ocumuj, 1, 2) == "99" ~ "IGNORADO",
  TRUE ~ data_matrimonios_2010$Ocumuj)
```

```{r}
unique(data_matrimonios_2010$Ocumuj)
#View(data_matrimonios_2010)
```


```{r}
categorias <- c("01", "03", "11", "12", "13", "14", "21", "22", "23", "24", "25", "26", "31", "32", "33", "34", "35", "41", "42", "43", "44", "51", "52", "54", "61", "62", "71", "72", "73", "74", "75", "81", "82", "83", "91", "92", "93", "94", "95", "96")

data_matrimonios_2011$Ocuhom <- case_when(
  substr(data_matrimonios_2011$Ocuhom, 1, 2) %in% categorias ~ substr(data_matrimonios_2011$Ocuhom, 1, 2),
  substr(data_matrimonios_2011$Ocuhom, 1, 2) == "97" ~ "NEOG",
  substr(data_matrimonios_2011$Ocuhom, 1, 2) == "99" ~ "IGNORADO",
  TRUE ~ data_matrimonios_2011$Ocuhom)
```

```{r}
unique(data_matrimonios_2011$Ocuhom)
#View(data_matrimonios_2010)
```


```{r}
categorias <- c("01", "03", "11", "12", "13", "14", "21", "22", "23", "24", "25", "26", "31", "32", "33", "34", "35", "41", "42", "43", "44", "51", "52", "54", "61", "62", "71", "72", "73", "74", "75", "81", "82", "83", "91", "92", "93", "94", "95", "96")

data_matrimonios_2011$Ocumuj <- case_when(
  substr(data_matrimonios_2011$Ocumuj, 1, 2) %in% categorias ~ substr(data_matrimonios_2011$Ocumuj, 1, 2),
  substr(data_matrimonios_2011$Ocumuj, 1, 2) == "05" ~ "NEOG",
  substr(data_matrimonios_2011$Ocumuj, 1, 2) == "53" ~ "51",
  substr(data_matrimonios_2011$Ocumuj, 1, 2) == "97" ~ "NEOG",
  substr(data_matrimonios_2011$Ocumuj, 1, 2) == "99" ~ "IGNORADO",
  TRUE ~ data_matrimonios_2011$Ocumuj)
```

```{r}
unique(data_matrimonios_2011$Ocumuj)
#View(data_matrimonios_2010)
```


```{r}
categorias <- c("01", "03", "11", "12", "13", "14", "21", "22", "23", "24", "25", "26", "31", "32", "33", "34", "35", "41", "42", "43", "44", "51", "52", "54", "61", "62", "71", "72", "73", "74", "75", "81", "82", "83", "91", "92", "93", "94", "95", "96")

data_matrimonios_2012$OCUHOM <- case_when(
  substr(data_matrimonios_2012$OCUHOM, 1, 2) %in% categorias ~ substr(data_matrimonios_2012$OCUHOM, 1, 2),
  substr(data_matrimonios_2012$OCUHOM, 1, 2) == "29" ~ "NEOG",
  substr(data_matrimonios_2012$OCUHOM, 1, 2) == "76" ~ "NEOG",
  substr(data_matrimonios_2012$OCUHOM, 1, 2) == "97" ~ "NEOG",
  substr(data_matrimonios_2012$OCUHOM, 1, 2) == "99" ~ "IGNORADO",
  TRUE ~ data_matrimonios_2012$OCUHOM)
```

```{r}
unique(data_matrimonios_2012$OCUHOM)
```


```{r}
categorias <- c("01", "03", "11", "12", "13", "14", "21", "22", "23", "24", "25", "26", "31", "32", "33", "34", "35", "41", "42", "43", "44", "51", "52", "54", "61", "62", "71", "72", "73", "74", "75", "81", "82", "83", "91", "92", "93", "94", "95", "96")

data_matrimonios_2012$OCUMUJ <- case_when(
  substr(data_matrimonios_2012$OCUMUJ, 1, 2) %in% categorias ~ substr(data_matrimonios_2012$OCUMUJ, 1, 2),
  substr(data_matrimonios_2012$OCUMUJ, 1, 2) == "53" ~ "51",
  substr(data_matrimonios_2012$OCUMUJ, 1, 2) == "97" ~ "NEOG",
  substr(data_matrimonios_2012$OCUMUJ, 1, 2) == "99" ~ "IGNORADO",
  TRUE ~ data_matrimonios_2012$OCUMUJ)
```

```{r}
unique(data_matrimonios_2012$OCUMUJ)
```



```{r}
campos_2010_h <- colnames(data_matrimonios_2010)
campos_2010_h[campos_2010_h == "Ocuhom"] <- "CIUOHOM"
colnames(data_matrimonios_2010) <- campos_2010_h
```

```{r}
campos_2010_m <- colnames(data_matrimonios_2010)
campos_2010_m[campos_2010_m == "Ocumuj"] <- "CIUOMUJ"
colnames(data_matrimonios_2010) <- campos_2010_m
```

```{r}
campos_2011_h <- colnames(data_matrimonios_2011)
campos_2011_h[campos_2011_h == "Ocuhom"] <- "CIUOHOM"
colnames(data_matrimonios_2011) <- campos_2011_h
```

```{r}
campos_2011_m <- colnames(data_matrimonios_2011)
campos_2011_m[campos_2011_m == "Ocumuj"] <- "CIUOMUJ"
colnames(data_matrimonios_2011) <- campos_2011_m
```

```{r}
campos_2012_h <- colnames(data_matrimonios_2012)
campos_2012_h[campos_2012_h == "OCUHOM"] <- "CIUOHOM"
colnames(data_matrimonios_2012) <- campos_2012_h
```

```{r}
campos_2012_m <- colnames(data_matrimonios_2012)
campos_2012_m[campos_2012_m == "OCUMUJ"] <- "CIUOMUJ"
colnames(data_matrimonios_2012) <- campos_2012_m
```


```{r}
data_matrimonios_2013$PUEHOM <- case_when(
  data_matrimonios_2013$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2013$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2013$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2013$PUEHOM)
```

```{r}
data_matrimonios_2014$PUEHOM <- case_when(
  data_matrimonios_2014$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2014$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2014$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2014$PUEHOM)
```

```{r}
data_matrimonios_2015$PUEHOM <- case_when(
  data_matrimonios_2015$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2015$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2015$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2015$PUEHOM)
```

```{r}
data_matrimonios_2016$PUEHOM <- case_when(
  data_matrimonios_2016$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2016$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2016$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2016$PUEHOM)
```

```{r}
data_matrimonios_2017$PUEHOM <- case_when(
  data_matrimonios_2017$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2017$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2017$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2017$PUEHOM)
```


```{r}
data_matrimonios_2018$PUEHOM <- case_when(
  data_matrimonios_2018$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2018$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2018$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2018$PUEHOM)
```

```{r}
data_matrimonios_2019$PUEHOM <- case_when(
  data_matrimonios_2019$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2019$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2019$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2019$PUEHOM)
```

```{r}
data_matrimonios_2020$PUEHOM <- case_when(
  data_matrimonios_2020$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2020$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2020$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2020$PUEHOM)
```

```{r}
data_matrimonios_2021$PUEHOM <- case_when(
  data_matrimonios_2021$PUEHOM %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2021$PUEHOM %in% c(4, 5) ~ 2, 
  data_matrimonios_2021$PUEHOM == 9 ~ 9, 
  TRUE ~ data_matrimonios_2021$PUEHOM)
```


```{r}
data_matrimonios_2013$PUEMUJ <- case_when(
  data_matrimonios_2013$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2013$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2013$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2013$PUEMUJ)
```

```{r}
data_matrimonios_2014$PUEMUJ <- case_when(
  data_matrimonios_2014$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2014$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2014$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2014$PUEMUJ)
```

```{r}
data_matrimonios_2015$PUEMUJ <- case_when(
  data_matrimonios_2015$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2015$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2015$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2015$PUEMUJ)
```

```{r}
data_matrimonios_2016$PUEMUJ <- case_when(
  data_matrimonios_2016$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2016$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2016$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2016$PUEMUJ)
```

```{r}
data_matrimonios_2017$PUEMUJ <- case_when(
  data_matrimonios_2017$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2017$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2017$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2017$PUEMUJ)
```


```{r}
data_matrimonios_2018$PUEMUJ <- case_when(
  data_matrimonios_2018$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2018$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2018$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2018$PUEMUJ)
```

```{r}
data_matrimonios_2019$PUEMUJ <- case_when(
  data_matrimonios_2019$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2019$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2019$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2019$PUEMUJ)
```

```{r}
data_matrimonios_2020$PUEMUJ <- case_when(
  data_matrimonios_2020$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2020$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2020$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2020$PUEMUJ)
```

```{r}
data_matrimonios_2021$PUEMUJ <- case_when(
  data_matrimonios_2021$PUEMUJ %in% c(1, 2, 3) ~ 1, 
  data_matrimonios_2021$PUEMUJ %in% c(4, 5) ~ 2, 
  data_matrimonios_2021$PUEMUJ == 9 ~ 9, 
  TRUE ~ data_matrimonios_2021$PUEMUJ)
```



```{r}
campos_2010_ph <- colnames(data_matrimonios_2010)
campos_2010_ph[campos_2010_ph == "Gethom"] <- "GETHOM"
colnames(data_matrimonios_2010) <- campos_2010_ph
```

```{r}
campos_2011_ph <- colnames(data_matrimonios_2011)
campos_2011_ph[campos_2011_ph == "Gethom"] <- "GETHOM"
colnames(data_matrimonios_2011) <- campos_2011_ph
```

```{r}
campos_2013_ph <- colnames(data_matrimonios_2013)
campos_2013_ph[campos_2013_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2013) <- campos_2013_ph
```

```{r}
campos_2014_ph <- colnames(data_matrimonios_2014)
campos_2014_ph[campos_2014_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2014) <- campos_2014_ph
```

```{r}
campos_2015_ph <- colnames(data_matrimonios_2015)
campos_2015_ph[campos_2015_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2015) <- campos_2015_ph
```

```{r}
campos_2016_ph <- colnames(data_matrimonios_2016)
campos_2016_ph[campos_2016_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2016) <- campos_2016_ph
```

```{r}
campos_2017_ph <- colnames(data_matrimonios_2017)
campos_2017_ph[campos_2017_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2017) <- campos_2017_ph
```

```{r}
campos_2018_ph <- colnames(data_matrimonios_2018)
campos_2018_ph[campos_2018_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2018) <- campos_2018_ph
```

```{r}
campos_2019_ph <- colnames(data_matrimonios_2019)
campos_2019_ph[campos_2019_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2019) <- campos_2019_ph
```

```{r}
campos_2020_ph <- colnames(data_matrimonios_2020)
campos_2020_ph[campos_2020_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2020) <- campos_2020_ph
```

```{r}
campos_2021_ph <- colnames(data_matrimonios_2021)
campos_2021_ph[campos_2021_ph == "PUEHOM"] <- "GETHOM"
colnames(data_matrimonios_2021) <- campos_2021_ph
```



```{r}
campos_2010_pm <- colnames(data_matrimonios_2010)
campos_2010_pm[campos_2010_pm == "Getmuj"] <- "GETMUJ"
colnames(data_matrimonios_2010) <- campos_2010_pm
```

```{r}
campos_2011_pm <- colnames(data_matrimonios_2011)
campos_2011_pm[campos_2011_pm == "Getmuj"] <- "GETMUJ"
colnames(data_matrimonios_2011) <- campos_2011_pm
```

```{r}
campos_2013_pm <- colnames(data_matrimonios_2013)
campos_2013_pm[campos_2013_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2013) <- campos_2013_pm
```

```{r}
campos_2014_pm <- colnames(data_matrimonios_2014)
campos_2014_pm[campos_2014_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2014) <- campos_2014_pm
```

```{r}
campos_2015_pm <- colnames(data_matrimonios_2015)
campos_2015_pm[campos_2015_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2015) <- campos_2015_pm
```

```{r}
campos_2016_pm <- colnames(data_matrimonios_2016)
campos_2016_pm[campos_2016_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2016) <- campos_2016_pm
```

```{r}
campos_2017_pm <- colnames(data_matrimonios_2017)
campos_2017_pm[campos_2017_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2017) <- campos_2017_pm
```

```{r}
campos_2018_pm <- colnames(data_matrimonios_2018)
campos_2018_pm[campos_2018_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2018) <- campos_2018_pm
```

```{r}
campos_2019_pm <- colnames(data_matrimonios_2019)
campos_2019_pm[campos_2019_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2019) <- campos_2019_pm
```

```{r}
campos_2020_pm <- colnames(data_matrimonios_2020)
campos_2020_pm[campos_2020_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2020) <- campos_2020_pm
```

```{r}
campos_2021_pm <- colnames(data_matrimonios_2021)
campos_2021_pm[campos_2021_pm == "PUEMUJ"] <- "GETMUJ"
colnames(data_matrimonios_2021) <- campos_2021_pm
```

Convertir de mayusculas a minusculas (data de 2010 y 2011)

``` {r}
names(data_matrimonios_2010) <- toupper(names(data_matrimonios_2010))
print(data_matrimonios_2010)
```

``` {r}
names(data_matrimonios_2011) <- toupper(names(data_matrimonios_2011))
print(data_matrimonios_2011)
```

Borrar las columnas que ya no son necesarias

``` {r}
data_matrimonios_2010 <- data_matrimonios_2010[, -which(names(data_matrimonios_2010) == "AÑOOCU")]
data_matrimonios_2010 <- data_matrimonios_2010[, -which(names(data_matrimonios_2010) == "AREAG")]
```

``` {r}
data_matrimonios_2011 <- data_matrimonios_2011[, -which(names(data_matrimonios_2011) == "AÑOOCU")]
```

``` {r}
data_matrimonios_2011 <- data_matrimonios_2011[, -which(names(data_matrimonios_2011) == "AREAG")]
```

``` {r}
data_matrimonios_2012 <- data_matrimonios_2012[, -which(names(data_matrimonios_2012) == "AREAG")]
```

``` {r}
# desde el 2012 a 2017 # AREAGOCU
data_matrimonios_2013 <- data_matrimonios_2013[, -which(names(data_matrimonios_2013) == "AREAGOCU")]
data_matrimonios_2014 <- data_matrimonios_2014[, -which(names(data_matrimonios_2014) == "AREAGOCU")]
data_matrimonios_2015 <- data_matrimonios_2015[, -which(names(data_matrimonios_2015) == "AREAGOCU")]
data_matrimonios_2016 <- data_matrimonios_2016[, -which(names(data_matrimonios_2016) == "AREAGOCU")]
data_matrimonios_2017 <- data_matrimonios_2017[, -which(names(data_matrimonios_2017) == "AREAGOCU")]
```



``` {r}
# Desde el 2015 en adelante # -> NUNUHO 
data_matrimonios_2015 <- data_matrimonios_2015[, -which(names(data_matrimonios_2015) == "NUNUHO")]
data_matrimonios_2016 <- data_matrimonios_2016[, -which(names(data_matrimonios_2016) == "NUNUHO")]
data_matrimonios_2017 <- data_matrimonios_2017[, -which(names(data_matrimonios_2017) == "NUNUHO")]
data_matrimonios_2018 <- data_matrimonios_2018[, -which(names(data_matrimonios_2018) == "NUNUHO")]
data_matrimonios_2019 <- data_matrimonios_2019[, -which(names(data_matrimonios_2019) == "NUNUHO")]
data_matrimonios_2020 <- data_matrimonios_2020[, -which(names(data_matrimonios_2020) == "NUNUHO")]
data_matrimonios_2021 <- data_matrimonios_2021[, -which(names(data_matrimonios_2021) == "NUNUHO")]

# -> NUNUMU
data_matrimonios_2015 <- data_matrimonios_2015[, -which(names(data_matrimonios_2015) == "NUNUMU")]
data_matrimonios_2016 <- data_matrimonios_2016[, -which(names(data_matrimonios_2016) == "NUNUMU")]
data_matrimonios_2017 <- data_matrimonios_2017[, -which(names(data_matrimonios_2017) == "NUNUMU")]
data_matrimonios_2018 <- data_matrimonios_2018[, -which(names(data_matrimonios_2018) == "NUNUMU")]
data_matrimonios_2019 <- data_matrimonios_2019[, -which(names(data_matrimonios_2019) == "NUNUMU")]
data_matrimonios_2020 <- data_matrimonios_2020[, -which(names(data_matrimonios_2020) == "NUNUMU")]
data_matrimonios_2021 <- data_matrimonios_2021[, -which(names(data_matrimonios_2021) == "NUNUMU")]

# -> AÑOOCU
data_matrimonios_2015 <- data_matrimonios_2015[, -which(names(data_matrimonios_2015) == "AÑOOCU")]
data_matrimonios_2016 <- data_matrimonios_2016[, -which(names(data_matrimonios_2016) == "AÑOOCU")]
data_matrimonios_2017 <- data_matrimonios_2017[, -which(names(data_matrimonios_2017) == "AÑOOCU")]
data_matrimonios_2018 <- data_matrimonios_2018[, -which(names(data_matrimonios_2018) == "AÑOOCU")]
data_matrimonios_2019 <- data_matrimonios_2019[, -which(names(data_matrimonios_2019) == "AÑOOCU")]
data_matrimonios_2020 <- data_matrimonios_2020[, -which(names(data_matrimonios_2020) == "AÑOOCU")]
data_matrimonios_2021 <- data_matrimonios_2021[, -which(names(data_matrimonios_2021) == "AÑOOCU")]
```