

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(dplyr)
library(knitr)
library(rpart)       # performing regression trees
library(rsample)     # data splitting 
library(rpart.plot)  # plotting regression trees
library(ipred)       # bagging
library(caret)       # bagging
library(randomForest)
library(doParallel)
```

```{r echo=FALSE}
data <- read.csv("data_final_parte2.csv")
```

``` {r}
set.seed(5)
expected_result <- data$diferenciaEdad
partition <- createDataPartition(y=expected_result, p=.70, list=F)
train_set <- data[partition,]
test_set <- data[-partition,]
```


```{r}
train_set <- train_set %>% mutate_at(c("diferenciaEdad"), as.factor)
test_set <- test_set %>% mutate_at(c("diferenciaEdad"), as.factor)
train_set <- train_set[,-c(6,7)]
```


```{r}
ct<-trainControl(method = "cv",number=5, verboseIter=T)
modelo_ac<-train(diferenciaEdad~.,data=train_set,method="J48",trControl = ct)
```

```{r}
modelo_ac
```

```{r}
y <- test_set[,-c(6, 7)]$diferenciaEdad
test_set <- test_set[,-c(6, 7)]
```


```{r}
ypred <- predict(modelo_ac, newdata = test_set)
ypred <- factor(ypred)
confusionMatrix(ypred, y)
```

## Modelos - Random Forest 

```{r}
cl <- makePSOCKcluster(5)
registerDoParallel(cl)
```

```{r Random Forest}
modelo_randomf <- randomForest(diferenciaEdad~.,train_set, na.action = na.omit, mtry=10, ntree=200, verbose=T)
summary(modelo_randomf)
```
```{r}
modelo_randomf
```

```{r}
stopCluster(cl)
```

```{r}
ypred_randomf <- predict(modelo_randomf, newdata = test_set)
ypred_randomf <- factor(ypred_randomf)
confusionMatrix(ypred_randomf, y)
```
```{r Random Forest}
modelo_rf_2 <- randomForest(diferenciaEdad~.,train_set, na.action = na.omit, mtry=4, ntree=500, verbose=T)
```

```{r Random Forest}
modelo_rf_3 <- randomForest(diferenciaEdad~.,train_set, na.action = na.omit, mtry=4, ntree=1000, verbose=T)
```

```{r Random Forest}
cores <- makeCluster(6)
registerDoParallel(cores = cores)
modelo_rf_4 <- randomForest(diferenciaEdad~.,train_set, na.action = na.omit, mtry=6, ntree=500, verbose=T)
```

```{r}
stopCluster(cores)
```


```{r Random Forest}
cores <- makeCluster(detectCores()-1)
registerDoParallel(cores = cores)
modelo_rf_5 <- randomForest(diferenciaEdad~.,train_set, na.action = na.omit, mtry=6, ntree=1000, verbose=T)
```

```{r Random Forest}
cores <- makeCluster(detectCores()-1)
registerDoParallel(cores = cores)
modelo_rf_6 <- randomForest(diferenciaEdad~.,train_set, na.action = na.omit, mtry=3, ntree=1000, verbose=T)
```

```{r}
stopCluster(cores)
```

---------------
```{r}
modelo_rf_2
```

```{r}
ypred_randomf2 <- predict(modelo_rf_2, newdata = test_set)
ypred_randomf2 <- factor(ypred_randomf2)
confusionMatrix(ypred_randomf2, y)
```
```{r}
modelo_rf_3
```


```{r}
ypred_randomf3 <- predict(modelo_rf_3, newdata = test_set)
ypred_randomf3 <- factor(ypred_randomf3)
confusionMatrix(ypred_randomf3, y)
```
```{r}
modelo_rf_4
```


```{r}
ypred_randomf4 <- predict(modelo_rf_4, newdata = test_set)
ypred_randomf4 <- factor(ypred_randomf4)
confusionMatrix(ypred_randomf4, y)
```
```{r}
modelo_rf_5
```



```{r}
ypred_randomf5 <- predict(modelo_rf_5, newdata = test_set)
ypred_randomf5 <- factor(ypred_randomf5)
confusionMatrix(ypred_randomf5, y)
```
```{r}
modelo_rf_6
```

```{r}
ypred_randomf6 <- predict(modelo_rf_6, newdata = test_set)
ypred_randomf6 <- factor(ypred_randomf6)
confusionMatrix(ypred_randomf5, y)
```
```{r}

cores <- makeCluster(5)
registerDoParallel(cores = cores)

control <- trainControl(method="repeatedcv", 
                        number=3, 
                        repeats=3,
                        allowParallel = TRUE)

tunegrid <- expand.grid(.mtry=c(3, 6, 9))

set.seed(123)

model <- train(diferenciaEdad~., data=train_set, 
                method="rf", 
                metric="Accuracy", 
                tuneGrid=tunegrid, 
                trControl=control,
                ntree=500)

```

```{r}
summary(model)
```

```{r}
plot(model)
```
